### ISSUE TITLE
评论提交不了

### ISSUE THREAD

**Issue by atangccc** [wenjing-xin/plugin-waline#1]
![1720445595359](https://github.com/wenjing-xin/plugin-waline/assets/111550294/36ff70f7-2621-4bda-b9ca-ab63cb66394b)
什么问题啊

**Comment by wenjing-xin** [comment]
评论区是正常显示，但是无法提交评论吗？数据库文件运行了嘛，或者sqlite 部署的需要替换数据库文件

**Comment by atangccc** [comment]
> 评论区是正常显示，但是无法提交评论吗？数据库文件运行了嘛，或者sqlite 部署的需要替换数据库文件
对呢，用的是halo商城waline 评论系统插件，该插件需要部署数据库吗

**Comment by wenjing-xin** [comment]
> > 评论区是正常显示，但是无法提交评论吗？数据库文件运行了嘛，或者sqlite 部署的需要替换数据库文件
> > 对呢，用的是halo商城waline 评论系统插件，该插件需要部署数据库吗

请在检查下你的 waline 评论系统部署吗。这是第三方评论系统，我已经在插件的说明文档说写了部署方式了
